server:
  port: 8082
  servlet:
    contextPath: /
spring:
  datasource:
    password: MysqlDonny@123
    url: jdbc:mysql://localhost:3306/musicastore?user=root
    driverClassName: com.mysql.cj.jdbc.Driver